apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: apphub-modified-trigger
  namespace: testkube
spec:
  resource: deployment    # pod, deployment, statefulset, daemonset, service, ingress, event, configmap
  resourceSelector:
    name: application-hub-hub-5c7d99ccf7-4rrw5  # which pod name we should be providing here? Like "application-hub-hub-7794f64bf4-slt89" ??
    namespace: proc
  execution: test
  event: modified
  action: run
  delay: 30s
  testSelector:
    name: apphubtest    ## or testsuite
    namespace: testkube

---

apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: eoxvs-modified-trigger
  namespace: testkube
spec:
  resource: deployment    # pod, deployment, statefulset, daemonset, service, ingress, event, configmap
  resourceSelector:
    name: eoxvs-harvester-584b8bc8bd-jfkl6  # which pod name we should be providing here? Like "application-hub-hub-7794f64bf4-slt89" ??
    namespace: proc
  execution: testsuite
  event: modified
  action: run
  delay: 30s
  testSelector:
    name: testkube-suite
    namespace: testkube





# apiVersion: tests.testkube.io/v1
# kind: TestTrigger
# metadata:
#   name: testtrigger-eodhp
#   namespace: default
# spec:
#   resource: deployment
#   resourceSelector:
#     labelSelector:
#       matchLabels:
#         testkube.io/tier: backend
#   event: modified
#   conditionSpec:
#     timeout: 100
#     delay: 2
#     conditions:
#     - type: Progressing
#       status: "True"
#       reason: "NewReplicaSetAvailable"
#       ttl: 60
#     - type: Available
#       status: "True"
#   probeSpec:
#     timeout: 50
#     delay: 1
#     probes:
#     - scheme: http
#       host: testkube-api-server
#       path: /health
#       port: 8088
#       headers:
#         X-Token: "12345"
#     - host: testkube-dashboard
#       port: 8080     
#   action: run
#   execution: testsuite
#   concurrencyPolicy: allow
#   testSelector:
#     name: sanity-test
#     namespace: frontend